---
# tasks file for plays/roles/ssh

# Ensure user/.ssh folder exits
- name: Make dan/.ssh folder if needed
  become: True
  file: 
    path: /home/{{ main_user }}/.ssh
    owner: dan
    group: sudo
    mode: 0700
    state: directory

# Copy auth_keys 
- name: Copy the authorized_keys file
  become: True
  copy: 
    src: authorized_keys 
    dest: /home/{{ main_user }}/.ssh/authorized_keys
    owner: dan
    group: sudo
    mode: 0600
  notify: restart sshd

# Copy ssh_config
- name: Copy the ssh_config file
  become: True
  copy: 
    src: ssh_config.conf
    dest: /etc/ssh/ssh_config.d/hard.conf
    owner: root
    group: root
    mode: 0444
  notify: restart sshd

# Copy sshd_config
- name: Copy the sshd_config file
  become: True
  copy: 
    src: sshd_config.conf
    dest: /etc/ssh/sshd_config.d/hard.conf
    owner: root
    group: root
    mode: 0411
  notify: restart sshd
