- hosts: servers
  roles:
    - ssh
  tags: ssh
  vars_files:
    - ../files/variables.yml
      
- hosts: test
  roles: 
    - role: ncpa_install_linux
    - role: register_with_xi
    - role: xi_apply_config
  tags: nagios
  vars_files:
    - ../files/variables.yml
 