
- hosts: servers
  gather_facts: true
  roles: 
    - base
    - ufw
  tags: base
  vars_files:
  - ../files/variables.yml
  - ../files/passwords.yml

- hosts: servers
  gather_facts: true
  roles:
    - ssh
  tags: ssh
  vars_files:
    - ../files/variables.yml
    - ../files/passwords.yml
      
- hosts: servers
  gather_facts: true
  roles:
    - observium
  tags: observium
  vars_files:
    - ../files/variables.yml
    - ../files/passwords.yml

#- hosts: servers
#  roles: 
#    - role: ncpa_install_linux
#    - role: register_with_xi
#    - role: xi_apply_config
#  tags: nagios
#  vars_files:
#    - ../files/variables.yml
 
#- hosts: all
#  roles: 
#    - crowdsec
#  tags: crowdsec
#  vars_files:
#    - ../files/variables.yml
#    - ../files/passwords.yml
 
#- hosts: nas
#  roles: 
#    - nas
#  vars_files:
#    - ../files/vars.yaml
#    - ../files/passwords.yml
#  tags: nas

