---

- hosts: servers
  vars_files:
    - ../files/variables.yml
  
# Updates
  tasks:
  - name: Run package updates
    ansible.builtin.dnf:
      name: "*"
      state: latest    
    when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' 
    
# Default packages

# Maintainance
  - name: Set timezone to America/Denver
    become: true
    community.general.timezone:
      name: "{{ timezone }}"

# Add main user to system

# Security
## SSH
## CrowdSec
## Tailscale
## Nagios Agent
