---

- hosts: all
  tasks: 
  - name: Gather facts up front
    ansible.builtin.gather_facts:

- hosts: all
  become: true
  gather_facts: false
  tasks: 
  - name: Update apt
    apt:
      update_cache: yes
      upgrade: yes
      autoremove: yes
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' 

- hosts: macbook
  become: true
  gather_facts: false
  tasks: 
  - name: Update brew
    community.general.homebrew:
      update_homebrew: true
      upgrade_all: true    
    when: ansible_distribution == 'Darwin' 
