---

- hosts: all

  vars_files:
    - ../files/passwords.yml

  tasks: 
  - name: Gather facts up front
    ansible.builtin.gather_facts:

- hosts: all

  vars_files:
    - ../files/passwords.yml

  become: true
  gather_facts: false
  tasks: 
  - name: Update apt
    apt:
      update_cache: yes
      upgrade: yes
      autoremove: yes
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' 

- hosts: all
  become: true
  gather_facts: false
  tasks: 
  - name: Upgrade dnf
    ansible.builtin.dnf:
      name: "*"
      state: latest    
    when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' 

- hosts: all
  become: true
  gather_facts: false
  tasks: 
  - name: Update pacman 
    community.general.pacman:
      update_cache: true
      upgrade: true
    when: ansible_distribution == 'Archlinux'  

- hosts: macbook
  become: true
  gather_facts: false
  tasks: 
  - name: Update brew
    community.general.homebrew:
      update_homebrew: true
      upgrade_all: true    
    when: ansible_distribution == 'Darwin' 
