all: 
  hosts: 
    dans-desktop.lan: # Fedora KDE 37 
      ansible_become_pass: '{{ dans_desktop_pass }}'
    dans-server.lan: # Ubuntu srv 22.04
      ansible_user: dan 
      ansible_become_pass: '{{ dans_server_pass }}'
    dans-mini.lan: # Ubuntu ser 22.04
      ansible_user: dan 
      ansible_become_pass: '{{ dans_mini_pass }}'
    dans-pisrv.lan: # Debian 11 bullseye
      ansible_become_pass: '{{ dans_pisrv_pass }}'
    dans-macbook.lan: # macOS Ventura
      ansible_become_pass: '{{ dans_mac_pass }}'
    dans-proxmox.lan: # Debian 11 bullseye
      ansible_become_pass: '{{ dans_prox_pass }}'
      ansible_user: root
    dans-dell.lan: # Fedora server 37
      ansible_become_pass: '{{ dans_dell_pass }}'

  vars: 
    ansible_user: dan
    ansible_connection: ssh

  children:
    servers:
      hosts:
        dans-server.lan:
        dans-mini.lan:
        dans-pisrv.lan:

    hypervisor:
      hosts:
        dans-mini.lan:

    pisrv:
      hosts:
        dans-pisrv.lan:

    desktop:
      hosts:
        dans-desktop.lan:

    macbook:
      hosts:
        dans-macbook.lan:
