all: 
  hosts: 
    dans-desktop.lan: 
      ansible_become_pass: '{{ dans_desktop_pass }}'
    dans-server.lan: 
      ansible_become_pass: '{{ dans_server_pass }}'
    dans-mini.lan: 
      ansible_become_pass: '{{ dans_mini_pass }}'
    dans-pisrv.lan:
      ansible_become_pass: '{{ dans_pisrv_pass }}'
    dans-macbook.lan:
      ansible_become_pass: '{{ dans_mac_pass }}'
    dans-proxmox.lan:
      ansible_become_pass: '{{ dans_prox_pass }}'
      ansible_user: root
    dans-dell.lan:
      ansible_become_pass: '{{ dans_dell_pass }}'
    dans-nagios.lan:
      ansible_become_pass: '{{ dans_dell_pass }}'

  vars: 
    ansible_user: dan
    ansible_connection: ssh

  children:
    servers:
      hosts:
        dans-server.lan:
        dans-mini.lan:
        dans-pisrv.lan:
        dans-nagios.lan:
        dans-proxmox.lan:

    hypervisor:
      hosts:
        dans-mini.lan:

    pisrv:
      hosts:
        dans-pisrv.lan:

    desktop:
      hosts:
        dans-desktop.lan:

    macbook:
      hosts:
        dans-macbook.lan:
