---
# tasks file for observium

- name: Install snmp
  become: true
  apt:
    name: snmpd
    state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' 
  tags: observium

- name: Copy snmp config file
  become: true
  ansible.builtin.template:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: '0600'
  tags: observium
  notify: restart snmp

- name: Enable snmp
  become: true
  ansible.builtin.service:
    name: snmpd
    enabled: true
  tags: observium

- name: Include ufw
  include_tasks: ufw.yml
  tags: observium
  
