---

- name: Allow snmp
  become: true
  community.general.ufw:
    rule: allow
    port: snmp
    src: '{{ item }}'
    proto: udp
  loop:
    - 10.10.10.0/24
    - 10.10.1.0/24
    - 100.0.0.0/8
  tags: observium
      
- name: reload ufw
  become: true
  community.general.ufw:
    state: reloaded
  tags: observium
